Import("env")

env.Append(
    CPPPATH=[
        "#/lib/u8g2",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
)


libenv = env.Clone(FW_LIB_NAME="u8g2")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.BuildFirmwareLibrary(sources)
Return("lib")
